# Generated by Django 3.0.3 on 2021-04-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
