products = [
    {
        '_id': '1',
        'name': 'vans',
        'image': "./images/vans.jpg",
        'description':'vans basket walk with hapiness',
        'brand': 'vans',
        'category':'shoes',
        'price': 15000,
        'countInStock': 25,
        'rating': 4.5,
        'numReviews': 12,
        'shop': 'ramco',
    },
    {
        '_id': '2',
        'name': 'airpod',
        'image': '/assets/images/airpod.jpg',
        'description':'airpod listen to music',
        'brand': 'apple',
        'category':'electronic',
        'price': 10000,
        'countInStock': 25,
        'rating': 4.5,
        'numReviews': 12,
        'shop': 'champion',
    },
    {
        '_id': '3',
        'name': 'short',
        'image':'/assets/images/chemise.jpeg',
        'description':'good shirt with you',
        'brand': 'loui vuiton',
        'category':'dress',
        'price': 5000,
        'countInStock': 5,
        'rating': 4.5,
        'numReviews': 12,
        'shop': 'champion',
    },
    {
        '_id': '4',
        'name': 'figurine jk',
        'image':'../assets/images/fig.jpg',
        'description':'good stuff to decor your house',
        'brand': 'fig',
        'category':'decoration',
        'price': 7.000,
        'countInStock': 4,
        'rating': 4.5,
        'numReviews': 12,
        'shop': 'champion',
    },
    {
        '_id': '5',
        'name': 'iphone8',
        'image':"https://dyw7ncnq1en5l.cloudfront.net/optim/product/52/52757/3164512c-iphone-11-pro__450_400.jpeg",
        'description':'stay connect with the world',
        'brand': 'apple',
        'category':'electronic',
        'price': 150.000,
        'countInStock': 25,
        'rating': 4.5,
        'numReviews': 12,
        'shop': 'ramco',
    },
    {
        '_id': '6',
        'name': 'xiaomi',
        'image':"https://images-na.ssl-images-amazon.com/images/I/510GdVKLkfL._AC_SX425_.jpg",
        'description':'xiaomi the best way to stay connect',
        'brand': 'xiaomi',
        'category':'electronic',
        'price': 15.000,
        'countInStock': 25,
        'rating': 4.5,
        'numReviews': 12,
        'shop': 'champion',
    },




    {
    "orderItems": [{"_id": 3, "name": "figurine", "price": "10000.00", "quantity": 2, "image": "/images/fig.jpg"}
,
{"_id": 4, "name": "airpods", "price": "9000.00", "quantity": 8, "image": "/images/airpod.jpg"}],
    "paymentMethod": "moov",
    "taxPrice": 120,
    "shippingPrice" : 150,
    "totalPrice": 15000,
    "shippingAddress": {
        "address": "Agoe-anome",
        "city": "Lome",
        "postalCode": "bp 42",
        "country": "togo"
    }

}
]